// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsxnahdynbvdkibzozod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzeG5haGR5bmJ2ZGtpYnpvem9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTE3MTAsImV4cCI6MjA2ODA2NzcxMH0.IwfGskmK1Ccvfpd6jrLs93NFMu0tkgcMDInm09AKrv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});